-- Copyright 2024 by Mahrud Sayrafi

-- 'profile' is an interpreter keyword, defined in d/profiler.dd,
-- which logs statistics of executed M2 code in 'ProfileTable'.
-- TODO: log the relationship between function calls and return
-- in an external format like Graphviz, pprof, etc.

needs "methods.m2"

head := () -> ("#run", "cost", "position")
form := (ttime, t, n, pairs, loc) -> (n,
    format(4,2,2,2,"e", 100 * t / ttime), loc)
tail := (ttime, tticks) -> (
    tticks, format(4,4,4,4,"e",ttime) | "s", "elapsed total")

-- SE variants include start/end timestamps for each entry,
-- enabled by the ShowStartEnd option of profileSummary
headSE := () -> ("#run", "cost", "start", "end", "position")
formSE := (ttime, tstart, t, n, pairs, loc) -> (
    fmtTime := s -> format(4,3,3,3,"e", s - tstart) | "s";
    starts := apply(pairs, first);
    ends   := apply(pairs, last);
    (n,
	format(4,2,2,2,"e", 100 * t / ttime),
	if n > 1 then stack apply(starts, fmtTime) else fmtTime min starts,
	if n > 1 then stack apply(ends,   fmtTime) else fmtTime max ends,
	loc))
tailSE := (ttime, tticks, tstart, tend) -> (
    tticks,
    format(4,4,4,4,"e",ttime) | "s",
    "0s",
    format(4,3,3,3,"e", tend - tstart) | "s",
    "elapsed total")

-- prints the statistics logged by the profiler in a readable table
profileSummary = method(Dispatch => Thing, Options => true)
profileSummary Thing := {MaxEntries => 20, ShowStartEnd => false} >> opt -> x ->
    profileSummary(if x === () then "" else first locate x, opt)
profileSummary String := {MaxEntries => 20, ShowStartEnd => false} >> opt -> filename -> (
    showSE := opt.ShowStartEnd;
    dataset := select(pairs ProfileTable,
	(k, v) -> match_filename toString k);
    if #dataset == 0 then return TABLE {
	if showSE then headSE() else head(),
	if showSE then tailSE(0,0,0,0) else tail(0,0)};
    (ttime, tticks, totPairs) := ProfileTable#"total";
    tstart := min apply(totPairs, first);
    tend   := max apply(totPairs, last);
    data := sort pairs hashTable(join, apply(dataset,
	    (k, v) -> if k =!= "total" then (v, {k})));
    rows := min(opt.MaxEntries, #data);
    high := reverse take(data, {#data - rows - 1, #data - 1});
    body := if showSE
	then apply(rows, i -> formSE_(ttime, tstart) splice high#i)
	else apply(rows, i -> form_ttime splice high#i);
    tailRow := if showSE then tailSE(ttime, tticks, tstart, tend)
	else tail(ttime, tticks);
    TABLE join({if showSE then headSE() else head()}, body, {tailRow}))
profileSummary = new Command from profileSummary

resetProfileTable = new Command from resetProfileTable

-- =====================================================================
-- flameGraph: render an SVG flame graph from ProfileTable data.
-- The profiler does not record M2 call stacks (M2_stack in d/profiler.dd
-- is C++-only), so the parent/child hierarchy is reconstructed by
-- interval containment of each invocation's [startWall, endWall] pair.
-- Acknowledgement: Code generated by AI
-- =====================================================================

flameGraph'xmlEscape := s -> (
    s = replace("&", "&amp;",  s);
    s = replace("<", "&lt;",   s);
    s = replace(">", "&gt;",   s);
    s = replace("\"", "&quot;", s);
    s)

-- warm-palette color (red→yellow) keyed by hash of the location string
flameGraph'color := loc -> (
    h := hash loc;
    if h < 0 then h = -h;
    hue   := 10 + (h % 41);            -- 10..50
    sat   := 55 + ((h // 41)   % 26);  -- 55..80
    light := 50 + ((h // 1066) % 16);  -- 50..65
    concatenate("hsl(", toString hue, ",",
	toString sat,   "%,", toString light, "%)"))

-- ~6.5px per char at 12px Verdana; conservative for label clipping
flameGraph'truncate := (text, maxPx) -> (
    if maxPx < 18 then ""
    else (
	maxChars := floor(maxPx / 6.5);
	if #text <= maxChars then text
	else if maxChars <= 1 then ""
	else substring(text, 0, maxChars - 1) | "…"))

-- build the SVG string from a list of {loc, start, end} records
flameGraph'render := (records, tstart, tend, opt) -> (
    width  := opt.Width;
    rowH   := 16;
    pad    := 30;
    n      := #records;
    span   := tend - tstart;
    if n == 0 or span <= 0 then return concatenate(
	"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
	"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"", toString width,
	"\" height=\"60\" font-family=\"Verdana,sans-serif\" font-size=\"12\">",
	"<text x=\"", toString(width // 2),
	"\" y=\"30\" text-anchor=\"middle\">no profile data</text></svg>\n");
    --
    xScale := width / span;
    -- sort by (start asc, end desc), keeping the original index
    sorted := sort apply(n, i -> ({records#i#1, -records#i#2}, i));
    order  := apply(sorted, p -> p#1);
    --
    depths  := new MutableHashTable;
    openStack := {}; -- list of (origIndex, end) for currently-open intervals
    for k to n - 1 do (
	idx := order#k;
	r := records#idx;
	while #openStack > 0 and (last openStack)#1 <= r#1 do
	    openStack = drop(openStack, -1);
	depths#idx = #openStack;
	openStack = append(openStack, (idx, r#2)));
    --
    maxDepth := max values depths;
    if instance(opt.MaxDepth, ZZ) then maxDepth = min(maxDepth, opt.MaxDepth);
    infoBarH := 24;
    bodyH    := (maxDepth + 1) * rowH;
    totalH   := pad + bodyH + infoBarH + 6;
    --
    -- one <g> per visible frame; clicking sets the bottom #fgInfo text
    -- to the data-info attribute (full, untruncated position + cost)
    frames := apply(n, i -> (
	    d := depths#i;
	    if d > maxDepth then return "";
	    r  := records#i;
	    w  := (r#2 - r#1) * xScale;
	    if w < opt.MinWidth then return "";
	    x   := (r#1 - tstart) * xScale;
	    y   := pad + (maxDepth - d) * rowH;
	    dur := r#2 - r#1;
	    pct := 100 * dur / span;
	    loc := flameGraph'xmlEscape(r#0);
	    info := flameGraph'xmlEscape(concatenate(
		    r#0,
		    " | total elapsed time: ", toString dur, "s",
		    ", start time: ", toString(r#1 - tstart), "s",
		    ", end time: ",   toString(r#2 - tstart), "s"));
	    label := flameGraph'truncate(r#0, w - 6);
	    labelEl := if #label > 0 then concatenate(
		"<text x=\"", toString(x + 3), "\" y=\"", toString(y + 12),
		"\" pointer-events=\"none\">",
		flameGraph'xmlEscape label, "</text>") else "";
	    concatenate(
		"<g style=\"cursor:pointer\" data-info=\"", info,
		"\" onclick=\"document.getElementById(&#39;fgInfo&#39;)",
		".textContent=this.getAttribute(&#39;data-info&#39;)\">",
		"<title>", loc, " &#x2014; ", toString dur, "s (",
		toString pct, "%)</title>",
		"<rect x=\"", toString x,
		"\" y=\"", toString y,
		"\" width=\"", toString w,
		"\" height=\"", toString(rowH - 1),
		"\" fill=\"", flameGraph'color(r#0), "\"/>",
		labelEl, "</g>")));
    --
    concatenate(
	"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
	"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"", toString width,
	"\" height=\"", toString totalH,
	"\" font-family=\"Verdana,sans-serif\" font-size=\"12\">\n",
	"<style>rect{stroke:white;stroke-width:0.5}rect:hover{opacity:0.85}</style>\n",
	"<rect x=\"0\" y=\"0\" width=\"", toString width,
	"\" height=\"", toString totalH, "\" fill=\"#fafafa\"/>\n",
	"<text x=\"", toString(width // 2),
	"\" y=\"20\" text-anchor=\"middle\" font-size=\"14\">",
	"M2 Profile Flame Graph &#x2014; ", toString n, " frames, ",
	toString span, "s elapsed</text>\n",
	concatenate frames,
	"<text id=\"fgInfo\" x=\"6\" y=\"", toString(totalH - 8),
	"\" font-family=\"monospace,monospace\" font-size=\"11\" fill=\"#333\">",
	"click a frame to see its full position</text>\n",
	"</svg>\n"))

flameGraph = method(Dispatch => Thing, Options => true)
flameGraph Thing := {
    MaxDepth   => infinity,
    MinWidth   => 0.5,
    Width      => 1200,
    OutputFile => null
    } >> opt -> x ->
    flameGraph(if x === () then "" else first locate x, opt)
flameGraph String := {
    MaxDepth   => infinity,
    MinWidth   => 0.5,
    Width      => 1200,
    OutputFile => null
    } >> opt -> filename -> (
    -- Filtering before tree-building can flatten the hierarchy if a frame's
    -- true parent lives in another file; matches profileSummary's semantics.
    records := flatten apply(pairs ProfileTable, (k, v) ->
	if k === "total" or not match(filename, toString k) then {}
	else (
	    loc := toString k;
	    apply(v#2, p -> {loc, first p, last p})));
    totPairs := if ProfileTable#?"total" then (ProfileTable#"total")#2 else {};
    tstart := if #totPairs > 0 then min apply(totPairs, first) else 0.;
    tend   := if #totPairs > 0 then max apply(totPairs, last)  else 0.;
    svg := flameGraph'render(records, tstart, tend, opt);
    fn := if opt.OutputFile === null then (
	t := temporaryFileName() | ".svg";
	addEndFunction(() -> if fileExists t then removeFile t);
	t) else toString opt.OutputFile;
    fn << svg << close;
    show URL urlEncode(rootURI | realpath fn);
    fn)
flameGraph = new Command from flameGraph

-- prints a list of lines which have been seen by the profiler so far
-- TODO: also highlight missing lines or sections within a line
-- TODO: compute the percentage of covered code
coverageSummary = method(Dispatch => Thing)
coverageSummary Thing := x -> coverageSummary if x === () then "" else first locate x
coverageSummary String := filename -> (
    body := sort select(toString \ keys ProfileTable, match_filename);
    stack join({"covered lines:"}, body))
coverageSummary = new Command from coverageSummary
